featureClass:
    firstorder: 
    glcm: 
    gldm: 
    glrlm: 
    glszm: 
    ngtdm: 
    shape: 
imageType:
    Exponential:
        binWidth: 12.253931191203186
        voxelArrayShift: 0
    Gradient:
        binWidth: 11.670445556640624
        voxelArrayShift: 0
    LBP2D:
        binWidth: 0.09
        voxelArrayShift: 0
    LoG:
        binWidth: 7.75294189453125
        sigma:
        - 1
        voxelArrayShift: 11637
    Logarithm:
        binWidth: 18.849220590567864
        voxelArrayShift: 52724
    Original:
        binWidth: 12.917415527236388
        voxelArrayShift: 564
    Square:
        binWidth: 12.260013153567126
        voxelArrayShift: 0
    SquareRoot:
        binWidth: 12.260013153567126
        voxelArrayShift: 0
    Wavelet:
        binWidth: 12.253931191203186
        voxelArrayShift: 0
setting:
    binWidth: 12.917415527236388
    force2D: true
    normalize: true
    normalizeScale: 1
    voxelArrayShift: 564

