featureClass:
    firstorder: 
    glcm: 
    gldm: 
    glrlm: 
    glszm: 
    ngtdm: 
    shape: 
imageType:
    Exponential:
        binWidth: 1.7526691391637135
        voxelArrayShift: 0
    Gradient:
        binWidth: 0.4733584976196289
        voxelArrayShift: 0
    LBP2D:
        binWidth: 0.09
        voxelArrayShift: 0
    LoG:
        binWidth: 1.3810769653320312
        sigma:
        - 1
        voxelArrayShift: 3132
    Logarithm:
        binWidth: 2.387328649462639
        voxelArrayShift: 272198096066184
    Original:
        binWidth: 1.8603710743300332
        voxelArrayShift: 13
    Square:
        binWidth: 1.7600053024456335
        voxelArrayShift: 0
    SquareRoot:
        binWidth: 1.7600053024456335
        voxelArrayShift: 0
    Wavelet:
        binWidth: 1.7526691391637135
        voxelArrayShift: 0
setting:
    binWidth: 1.8603710743300332
    force2D: true
    normalize: true
    normalizeScale: 1
    voxelArrayShift: 13

