featureClass:
    firstorder: 
    glcm: 
    gldm: 
    glrlm: 
    glszm: 
    ngtdm: 
    shape: 
imageType:
    Exponential:
        binWidth: 37.489924114720615
        voxelArrayShift: 0
    Gradient:
        binWidth: 10.57251953125
        voxelArrayShift: 0
    LBP2D:
        binWidth: 0.09
        voxelArrayShift: 0
    LoG:
        binWidth: 31.8578271484375
        sigma:
        - 1
        voxelArrayShift: 714904
    Logarithm:
        binWidth: 61.40927155231631
        voxelArrayShift: 2449330960240649
    Original:
        binWidth: 40.80615439745125
        voxelArrayShift: 183
    Square:
        binWidth: 37.499924004231914
        voxelArrayShift: 0
    SquareRoot:
        binWidth: 37.499924004231914
        voxelArrayShift: 0
    Wavelet:
        binWidth: 37.489924114720615
        voxelArrayShift: 0
setting:
    binWidth: 40.80615439745125
    force2D: true
    normalize: false
    normalizeScale: 1
    voxelArrayShift: 183

