---
# generic for dataset
input_path: "../../data/PROSTATEx/ProstateX/" # path containing the input images
dataset_information_path: "dataset_information" # path for the output dataset information (spacing, voxel info)
masks_path: "../../data/PROSTATEx/ProstateX/aggregated-labels-lesion" # path to masks
mask_pattern: "*DWI*nii.gz" # pattern that will be used to glob masks
radiomic_settings_path: "config-feature-extraction" # path to directory which contains/will contain settings files
patterns: # patterns that will be used to glob the input images
  adc: "ADC/*.nii.gz"
  hbv: "DWI/*.nii.gz"
# very specific application: if an MRI from key has maximum > [0], it is multiplied by [1]
# useful for ADC in different orders of magnitude
conditional_multiplication: 
  adc: [1000,0.001]
# specific for output
radiomic_features_path: "../../data/PROSTATEx/radiomic_features/registration-none-adc-dwi" # output path for radiomic features
# meta parameters
dataset_id: "PROSTATEx" # id for the dataset (for the output files in dataset information)
registration: "none" # registration type
id_pattern: "P[A-Za-z]+[0-9]+" # pattern to extract ID from path
